import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import Header from "@/components/Header";

const rubik = Rubik({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "IP Address Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${rubik.className} min-h-screen`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
